/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinhaNumeroRouteImport } from './routes/linha.$numero'
import { Route as GestorLineIdRouteImport } from './routes/gestor.$lineId'

const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaNumeroRoute = LinhaNumeroRouteImport.update({
  id: '/linha/$numero',
  path: '/linha/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorLineIdRoute = GestorLineIdRouteImport.update({
  id: '/$lineId',
  path: '/$lineId',
  getParentRoute: () => GestorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestor': typeof GestorRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/gestor/$lineId': typeof GestorLineIdRoute
  '/linha/$numero': typeof LinhaNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestor': typeof GestorRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/gestor/$lineId': typeof GestorLineIdRoute
  '/linha/$numero': typeof LinhaNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestor': typeof GestorRouteWithChildren
  '/motorista': typeof MotoristaRoute
  '/gestor/$lineId': typeof GestorLineIdRoute
  '/linha/$numero': typeof LinhaNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestor'
    | '/motorista'
    | '/gestor/$lineId'
    | '/linha/$numero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gestor' | '/motorista' | '/gestor/$lineId' | '/linha/$numero'
  id:
    | '__root__'
    | '/'
    | '/gestor'
    | '/motorista'
    | '/gestor/$lineId'
    | '/linha/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestorRoute: typeof GestorRouteWithChildren
  MotoristaRoute: typeof MotoristaRoute
  LinhaNumeroRoute: typeof LinhaNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha/$numero': {
      id: '/linha/$numero'
      path: '/linha/$numero'
      fullPath: '/linha/$numero'
      preLoaderRoute: typeof LinhaNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/$lineId': {
      id: '/gestor/$lineId'
      path: '/$lineId'
      fullPath: '/gestor/$lineId'
      preLoaderRoute: typeof GestorLineIdRouteImport
      parentRoute: typeof GestorRoute
    }
  }
}

interface GestorRouteChildren {
  GestorLineIdRoute: typeof GestorLineIdRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorLineIdRoute: GestorLineIdRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestorRoute: GestorRouteWithChildren,
  MotoristaRoute: MotoristaRoute,
  LinhaNumeroRoute: LinhaNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
